[workspace]
members = ["bindings/c"]

[workspace.package]
version = "0.2.0"
authors = ["Chaoses-Ib"]
homepage = "https://github.com/Chaoses-Ib/IbPinyinLib"
repository = "https://github.com/Chaoses-Ib/IbPinyinLib"
license = "MIT"
keywords = ["pinyin", "cjk"]

[package]
name = "ib-pinyin"
edition = "2021"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraystring = "0.3.0"
bitflags = "2.4.1"
regex = "1.10.2"

[features]
inmut-data = []
minimal = ["inmut-data"]
